name: sec-ia-agent
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.8
  - pip
  - pip:
    - fastapi==0.109.2
    - uvicorn==0.27.1
    - python-multipart==0.0.6
    - jinja2==3.1.3
    - aiofiles==23.2.1
    - python-jose==3.3.0
    - passlib==1.7.4
    - bcrypt==4.1.2
    - python-dotenv==1.0.0
    - sqlalchemy==2.0.25
    - alembic==1.13.1
    - pandas==2.1.4
    - plotly==5.18.0
    - requests==2.31.0
    - pydantic==1.10.13
    - prometheus-client==0.17.1
    - aiohttp==3.7.4
    - loki-client==0.0.1
    - thehive4py==1.8.0
    - cortex4py==2.1.0